[tool.mypy]
ignore_missing_imports = true
# plugins = "numpy.typing.mypy_plugin"
python_version = "3.10"
show_error_codes = true
warn_unused_ignores = true

[tool.pyright]
pythonVersion = "3.10"
typeCheckingMode = "basic"

reportMissingTypeStubs = false

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
extend-select = ["F", "E", "W", "I", "N", "UP", "PGH"]
ignore = ["N817"]
